version: '3'
services:
  reverse-proxy:
    build: ./nginx
    image: reverse-proxy
    ports:
     - 80:80
     - 443:443
    depends_on:
     - frontend
     - backend
  
  mongodb:
    image: mongo
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
     - mongodbdata:/data/db

  backend:
    build: ./backend
    image: backend
    environment:
     - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
    depends_on:
     - mongodb
    restart: on-failure

  frontend:
    build: ./frontend
    image: frontend

  mongo-express:
    image: mongo-express
    environment:
     - ME_CONFIG_MONGODB_SERVER=mongodb
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
     - ME_CONFIG_SITE_BASEURL=/mongo-express
     - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
     - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}

volumes:
  mongodbdata:
    driver: local